---
title: Interactions retain the co-phylogenetic matching that communities lost
short: co-phylogenetic matching in space
keyword:
  - species interactions
  - host-parasites
  - phylogenetic congruence
  - network cophylogeny
  - community phylogenetics
date: 2017-03-02T00:00:00.000Z
abstract: >
  Both species and their interactions are affected by changes that occur at
  evolutionary time-scales, and these changes shape both ecological communities
  and their phylogenetic structure. That said, extant ecological community
  structure is contingent upon random chance, environmental filters, and local
  effects. It is therefore unclear how much ecological signal local communities
  should retain. Here we show that, in a host--parasite system where species
  interactions vary substantially over a continental gradient, the ecological
  significance of individual interactions is maintained across different scales.
  Notably, this occurs despite the fact that observed community variation at the
  local scale frequently tends to weaken or remove community-wide phylogenetic
  signal. When considered in terms of the interplay between community ecology
  and coevolutionary theory, our results demonstrate that individual
  interactions are capable and indeed likely to show a consistent signature of
  past evolutionary history even when woven into communities that do not.
author:
  - family: Poisot
    given: Timothée
    affiliations:
      - 1
      - 2
      - 3
    email: timothee.poisot@umontreal.ca
    id: tp
    orcid: 0000-0002-0735-5184
  - family: Stouffer
    given: Daniel B.
    affiliations:
      - 1
    id: dbs
affiliation:
  - id: 1
    text: >-
      Centre for Integrative Ecology, School of Biological Sciences, University
      of Canterbury, Christchurch, New Zealand
  - id: 2
    text: >-
      Université de Montréal, Département de Sciences Biologiques, Montréal,
      Canada
  - id: 3
    text: 'Québec Centre for Biodiversity Sciences, Montréal, Canada'
...
